### ISSUE TITLE
Define 2nd afternoon topic

### ISSUE THREAD

**Issue by katrinleinweber** [vdb-org/2019-06-26-blb-karlsruhe#10]
@T45A [asked in #8](https://github.com/vdb-org/2019-06-26-blb-karlsruhe/pull/8#issuecomment-484096909): What is your opinion about Day2 "Firefox Development Tool/Firebug" or "Python"?

Please see my initial reply there and let's discuss the possibilities here. In German is fine as well ;-)

**Comment by Scheuble** [comment]
Vom Ortskommittee in Karlsruhe kam nun noch ein anderer Vorschlag: "Wir sind der Meinung, dass im Veranstaltungsprogramm unbedingt noch die Lesson zu OpenRefine aufgenommen werden sollte. Falls die beiden Instruktoren das nicht anbieten, würde sich auch Herr Weber bereit erklären, den Teil zu OpenRefine zu übernehmen. Und statt GitHub würden wir - falls die Instruktoren das auch wollen - vorschlagen, eine Einführung in Python zu machen."

**Comment by katrinleinweber** [comment]
Dann sollten wir Herr Weber willkommen heißen :-) 

> falls die Instruktoren das auch wollen

spielt IMHO eine untergeordnete Rolle, denn [die **Themenwahl ist der 1. Punkt** in der Checkliste für Gastgeber](https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html). Daraus ergibt sich, welche Instructors eingeladen werden bzw. was sie vorbereiten sollten.

**Comment by Scheuble** [comment]
Das Programm des ersten Tages kann sehr gerne so bleiben. Da Herr Weber bereit ist, OpenRefine zu übernehmen, würden wir dies für Tag 2 wieder auf die Agenda setzen. Ob Python statt Github eine Option ist, hängt davon ab, ob es eine/n Instruktor/in dafür gibt. Das kann ich nicht abschätzen.

**Comment by katrinleinweber** [comment]
@konrad lehrt sonst meistens Python. Ich selbst [habe in Marburg](https://github.com/evamarik/2018-06-25-marburg/blame/gh-pages/_includes/lc/schedule.html#L10) die [ersten paar Episodes](https://librarycarpentry.org/lc-python-intro/) gelehrt, nutze Python aber selbst (noch) nicht im Arbeitsalltag.

**Comment by konrad** [comment]
@Tillsa oder ich können Python gerne übernehmen und haben das auch schon sehr häufig unterrichtet.

**Comment by loadbrain** [comment]
Hallo @ alle,
Ich bin ja noch kein Instructor, mache den Kurs am 1.7. und 2.7.
Von daher und da ich ja sowas noch nicht gemacht habe würde ich erstmal nur als Helfer tätig sein.

**Comment by katrinleinweber** [comment]
Den vom [VDB-Aufrauf kürzlich](https://www.vdb-online.org/2019/03/14/call-for-instructors-als-library-carpenter-skills-zum-praktischen-umgang-mit-daten-im-bibliotheksalltag-vermitteln/)? Cool! Willkommen an Bord :-)

Ich übernehme also die Shell (bereite damit gerade einen DSpace-Import vor), Git nehmen wir raus, dafür Python & OpenRefine rein.

@loadbrain: Bock den PR für Obiges [auf Basis von `schedule.html` zu erstellen](https://github.com/vdb-org/2019-06-26-blb-karlsruhe/edit/gh-pages/_includes/lc/schedule.html)? Dort zu editieren, und dann unten "Propose change" müsste gehen ;-)

**Comment by loadbrain** [comment]
Hallo,
Ja genau, VDB Aufruf.
Wie gesagt, ich würde lieber erstmal nur zusehen statt gleich openrefine lesson zu machen, da ich sowas ja noch nicht gemacht habe und auch noch gar kein Instructor bin. 
Aber wenn es nicht anders geht, jemand fehlt kann ich mir was überlegen... Aber mir wäre es lieber erstmal die Instructor Sache hinter mich zu bringen und hier nur zuzusehen..

**Comment by katrinleinweber** [comment]
So wie ich das bisher sehe, macht niemand sonst OpenRefine. Und nur deßwegen Git zu lehren, weil dafür Instructors da wären, ist IMHO weniger sinnvoll, als die Vorschläge des Ortskommittees umzusetzen.

Wichtiger als "schon Instructor oder nicht" dürfte Arbeitserfahrung damit sein, und Zeit zur Vorbereitung der [Standard-Lesson](https://librarycarpentry.org/lc-open-refine/) ;-)

**Comment by loadbrain** [comment]
Ok, wenn ich das nehmen kann, dann kann ich das machen.
Ihr müsstet mir nur sagen wie das genau abläuft, also was genau ich alles vorbereiten muss.
Und ich habe ja noch den ersten Tag um Euch zuzuschauen... ;-)

@katrinleinweber: schedule.html habe ich angepasst

**Comment by Scheuble** [comment]
Wenn ich es richtig sehe, haben wir nun das Programm rund bekommen (Data Intro: vermutlich Katrin Leinweber oder Konrad Förstner); Shell: Katrin Leinweber; Python: Konrad Förstner; OpenRefine: Ralf Weber) OpenRefine. Vielen herzlichen Dank Ihnen allen dafür. Git habe ich im Programm durch Python ersetzt. Als OpenRefine noch draußen habe, haben wir auch die entsprechende Erläuterung aus der Seite genommen. Wir werden versuchen, die Passage wieder einzufügen.

**Comment by katrinleinweber** [comment]
> Data Intro

Dazu kann ich was beitragen, aber wir alle sollten in der Intro mit den Leuten diskutieren, und vielleicht konkrete Beispiele für die später folgenden Themen aus unserem Arbeitsalltag mitbringen. Für Reg-Ex und Shell hätte ich was: https://github.com/TIBHannover/PICA-kulatur/

> Git habe ich im Programm durch Python ersetzt.

Hab's via #11 veröffentlicht ;-)

> Wir werden versuchen, die Passage wieder einzufügen.

`git revert` [`1ce9dde6`](https://github.com/vdb-org/2019-06-26-blb-karlsruhe/commit/1ce9dde60c6caf265f7cf81a28d4a938edd042da) falls dieses Repo auch offline vorliegt ;-) Wenn nicht: die dort roten Zeilen in [die `index.md` kopieren & einen neuen Commit erzeugen](https://github.com/vdb-org/2019-06-26-blb-karlsruhe/edit/gh-pages/index.md).

In solchen "Rollen rückwärts"-Sitautionen sind übrigens zusammenfassende und erklärende Commit-Messages nützlicher, als die paar Sekunden Zeitersparnis, wenn man einfach [GitHubs Standard-Message "Update ..."](https://github.com/vdb-org/2019-06-26-blb-karlsruhe/commits/gh-pages) so lässt ;-)

**Comment by loadbrain** [comment]
Im Syllabus sollte Git dann auch noch ersetzt werden, oder?

**Comment by katrinleinweber** [comment]
Stimmt. So ↗️ in Ordnung?

**Comment by loadbrain** [comment]
Soweit schon mal. Und weiter oben unter Syllabus wird es noch aufgelistet. Da sollte dann evtl. Python rein?

**Comment by katrinleinweber** [comment]
Hier dürfen alle editieren: https://github.com/vdb-org/2019-06-26-blb-karlsruhe/edit/gh-pages/index.md ;-)

Ich habe nach anderen "Git"-Stellen gesucht und keine bemerkt, die unbedingt raus *müssen*.

**Comment by RealLinna** [comment]
Ich hab mich kurzfristig als Helfer für den 27.6. angemeldet!
